- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload certificates
  command: systemctl restart etcd
  when: etcd_tls_enabled