---
all:
  children:
    ROUTERS:
      children:
        router-1:
      vars:
        tarantool_config_group:
          app:
            module: app.vshard_bootstrapper
          sharding:
            roles: [router]
          roles:
            - roles.crud-router
            - roles.metrics-export
            - dictionary.roles.router
          roles_cfg:
            roles.crud-router:
              stats: true
              stats_driver: metrics
              stats_quantiles: true
              stats_quantile_tolerated_error: 0.001
              stats_quantile_age_buckets_count: 5
              stats_quantile_max_age_time: 180
    STORAGES:
      children:
        storage-1:
      vars:
        tarantool_config_group:
          sharding:
            roles: [storage]
          roles:
            - roles.crud-storage
            - roles.expirationd
            - roles.metrics-export
            - dictionary.roles.storage
          memtx:
            memory: 536870912			
          roles_cfg:
            roles.expirationd: []
    storage-1:
      hosts:
        storage-1-1:
      vars:
        replicaset_alias: storage-1
        tarantool_config_replicaset:
          bootstrap_leader: storage-1-1
          replication:
            bootstrap_strategy: config
    router-1:
      hosts:
        router-1:
      vars:
        replicaset_alias: router-1	
    tarantooldb_1:
      hosts:
        storage-1-1:
          iproto:
            listen:
            - uri: 192.168.0.105:3301
            advertise:
              client: 192.168.0.105:3301
          roles_cfg:
            roles.metrics-export:
              http:
                - listen: 8181
                  endpoints:
                    - path: /metrics
                      format: prometheus
        router-1:
          iproto:
            listen:
            - uri: 192.168.0.105:3310
            advertise:
              client: 192.168.0.105:3310
          roles_cfg:
            roles.metrics-export:
              http:
                - listen: 8190
                  endpoints:
                    - path: /metrics
                      format: prometheus
      vars:
        ansible_host: 192.168.0.105
        
  vars:
    cartridge_cluster_cookie: tarantooldbcookie
    ansible_ssh_common_args: -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    ansible_ssh_retries: 5
    cartridge_app_name: tarantooldb
    tarantool_3_0_version_support: true
    tarantool_config_etcd_endpoints:
      - http://192.168.0.105:2379
    # ETCD vars for etcd_3_0
    etcd_host: 92.168.0.105
    etcd_port: 2379
    # ETCD vars for backup
    cartridge_etcd_host: 92.168.0.105
    cartridge_etcd_port: 2379
    tarantool_config_global:
      iproto:
        advertise:
          peer:
            login: replicator
          sharding:
            login: storage
      credentials:
        users:
          replicator:
            password: 'replicator_password'
            roles:
            - replication
            - dictionary_api_executor
          storage:
            password: 'storage_password'
            roles:
            - sharding
          admin:
            password: 'secret-cluster-cookie'
            roles:
            - super
          client:
            password: 'secret'
            roles:
            - super