# Prometheus configuration for Tarantool metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tarantool'
    metrics_path: '/metrics'
    static_configs:
      - targets:
                - '192.168.0.105:8181'
                - '192.168.0.105:8182'
                - '192.168.0.105:8183'
                - '192.168.0.105:8184'
                - '192.168.0.105:8190'
                - '192.168.0.105:8191'
        
